spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  batch:
    job:
      # only execute the following job or jobs - otherwise spring batch will attempt to launch all jobs
      names: parentJob

