spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  mail:
    host: smtp.gmail.com
    port: 587
    username: <yourusername>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    password: <yourpassword>
udemy:
  recipient: <yourrecipient>

